export type CareerBoardTier =
  | 'AI Research'
  | 'Quant'
  | 'National Lab'
  | 'Aerospace'
  | 'Semiconductor'
  | 'Deep Tech'
  | 'Sci Software'
  | 'Robotics'
  | 'Other';

export interface CareerBoardJob {
  id: string;
  company: string;
  role: string;
  tier: CareerBoardTier | string;
  link: string;
  fit: number;
  grad: string;
  exp: string;
  tags: string[];
  special: string;
  bullets: string[];
  source?: 'seed' | 'user';
  addedAt?: number;
}

export const CAREER_BOARD_SEED: CareerBoardJob[] = [
  { id: 'anthropic-re', company: 'Anthropic', role: 'Research Engineer, ML', tier: 'AI Research',
    link: 'https://www.anthropic.com/careers',
    fit: 92, grad: 'MS acceptable; open req year-round',
    exp: 'Strong ML engineering + independent research', tags: ['remote-friendly', 'AI'],
    special: 'Independent research, blog posts, or OSS contributions count more than credentials.',
    bullets: ['~50% of technical staff have PhDs; MS + strong projects viable', 'Physics analogy explicit in team culture', 'SF / NYC / remote-friendly'] },
  { id: 'openai-residency', company: 'OpenAI', role: 'Residency Program (6mo)', tier: 'AI Research',
    link: 'https://openai.com/residency/',
    fit: 88, grad: 'Bridge for non-CS technical grads (physics fits explicitly)',
    exp: 'Strong quantitative background + coding', tags: ['bridge', 'AI', 'SF'],
    special: 'Program designed for physics/math/eng transitioning into AI. 6-month paid.',
    bullets: ['Explicit target audience: physics + math + adj. sciences', 'Path to full-time RE / RS after residency', 'San Francisco onsite'] },
  { id: 'deepmind-re', company: 'Google DeepMind', role: 'Research Engineer / Student Researcher', tier: 'AI Research',
    link: 'https://deepmind.google/careers/',
    fit: 84, grad: 'MS OK for Research Engineer; Student Researcher during MS possible',
    exp: 'Python, PyTorch/JAX, publications a plus', tags: ['London/MTV', 'AI'],
    special: 'Student Researcher runs during degree; RE takes new grads with strong portfolio.',
    bullets: ['Physics-flavored teams (Science, Weather, Fusion)', 'Application windows are tight — apply early', 'Mountain View, London, Zurich'] },
  { id: 'meta-fair', company: 'Meta (FAIR / GenAI)', role: 'Research Engineer, New Grad', tier: 'AI Research',
    link: 'https://www.metacareers.com/jobs/?is_leadership=0&roles[0]=Research',
    fit: 78, grad: 'Bachelors/MS with research experience',
    exp: 'PyTorch, distributed training a plus', tags: ['Menlo Park', 'AI'],
    special: 'New grad RE requires research output (papers, OSS, blog).',
    bullets: ['FAIR sub-teams overlap with physical sim + reasoning', 'New grad L4 comp ~$400K TC in bay area', 'Reference from someone on team helps a lot'] },
  { id: 'nvidia-dl', company: 'NVIDIA', role: 'Deep Learning Research Engineer, NCG', tier: 'AI Research',
    link: 'https://www.nvidia.com/en-us/about-nvidia/careers/',
    fit: 76, grad: 'MS strongly preferred for research roles',
    exp: 'CUDA, PyTorch, systems-level knowledge', tags: ['Santa Clara', 'AI', 'hybrid'],
    special: 'Physics-simulation groups (Modulus, Omniverse) actively hire physics grads.',
    bullets: ['Modulus & Earth-2 teams want physics + ML dual', 'New college grad program has clear pipeline', "Search 'NCG' + 'Research' on careers site"] },
  { id: 'cohere-mle', company: 'Cohere', role: 'Machine Learning Engineer', tier: 'AI Research',
    link: 'https://cohere.com/careers',
    fit: 66, grad: 'Open — MS + projects sufficient',
    exp: 'Applied ML, LLM training/serving', tags: ['Toronto/SF/remote', 'AI'],
    special: 'Enterprise LLM focus; less basic-research than Anthropic.',
    bullets: ['Smaller company — one strong project can carry app', 'Distributed team including Canada + US', 'Roles rotate on their board — check monthly'] },

  { id: 'citadel-qra', company: 'Citadel', role: 'Quantitative Research Analyst (New Grad)', tier: 'Quant',
    link: 'https://www.citadel.com/careers/details/quantitative-research-analyst-university-graduate-us/',
    fit: 91, grad: 'BS/MS in physics/math/CS/stats — 2027 grad fits',
    exp: 'Strong probability, stats, Python, coding challenge', tags: ['NYC', 'Miami', 'Greenwich'],
    special: 'Base $235K–$300K + guaranteed bonus. OA is hard — practice probability puzzles.',
    bullets: ['Physics is a canonical pipeline for QRA', 'Multi-round interview: OA → math → research', 'Applications open May–Sep for following year'] },
  { id: 'citsec-qra', company: 'Citadel Securities', role: 'Quantitative Research Analyst (New Grad)', tier: 'Quant',
    link: 'https://www.citadelsecurities.com/careers/details/quantitative-research-analyst-university-graduate-us/',
    fit: 90, grad: 'BS/MS quantitative — 2027 target',
    exp: 'Coding + stats + market-making intuition', tags: ['NYC', 'Miami'],
    special: '$225K–$300K base; sister firm to Citadel but market-making not hedge fund.',
    bullets: ['Faster loop than Citadel main', "Ideal for 'I like the math not the finance' physicists", 'OA emphasizes speed + accuracy'] },
  { id: 'jane-street-qr', company: 'Jane Street', role: 'Quantitative Researcher (New Grad)', tier: 'Quant',
    link: 'https://www.janestreet.com/join-jane-street/position/',
    fit: 89, grad: 'Any quantitative degree; MS common',
    exp: 'OCaml learned on job; math heavy interviews', tags: ['NYC', 'London', 'hybrid'],
    special: 'Probability/math interview heavy; culture-fit critical.',
    bullets: ['Publishes puzzle sets — do the monthly puzzles as prep', 'Referral useful; smaller firm than Citadel', 'No dress code, functional programming culture'] },
  { id: 'two-sigma-qr', company: 'Two Sigma', role: 'Quantitative Researcher (New Grad)', tier: 'Quant',
    link: 'https://careers.twosigma.com/',
    fit: 86, grad: 'MS/PhD preferred for research; MS fits',
    exp: 'Statistics, ML, Python', tags: ['NYC', 'hybrid'],
    special: 'Strong data-science + ML bent among quant shops.',
    bullets: ['More engineering-heavy than pure quant firms', 'Two Sigma Labs is a research-oriented sub-org', 'Housing / relocation package generous'] },
  { id: 'deshaw-qa', company: 'D. E. Shaw', role: 'Quantitative Analyst (New Grad)', tier: 'Quant',
    link: 'https://www.deshaw.com/careers',
    fit: 85, grad: 'MS/PhD strongly preferred; MS OK with output',
    exp: 'Probability, coding, research background', tags: ['NYC'],
    special: "Interview is legendary probability set; prep with 'Heard on the Street'.",
    bullets: ['Historically strong physics pipeline', 'Comp table publicly circulated; competitive with Citadel', 'Application windows Sep–Nov for following year'] },
  { id: 'hrt-qr', company: 'Hudson River Trading', role: 'Quantitative Researcher / Algo Developer', tier: 'Quant',
    link: 'https://www.hudsonrivertrading.com/careers/',
    fit: 82, grad: 'MS/PhD in quantitative field',
    exp: 'C++ or Python, low-latency mindset a plus', tags: ['NYC', 'Chicago', 'remote-ish'],
    special: 'Very engineering-heavy; strong CS chops help more than at pure quant.',
    bullets: ["'Core Developer' and 'Algo Developer' both open to new grads", 'OA is engineering-focused, not pure prob', 'Small teams, high autonomy'] },
  { id: 'jump-qr', company: 'Jump Trading', role: 'Quantitative Researcher (New Grad)', tier: 'Quant',
    link: 'https://www.jumptrading.com/careers/',
    fit: 80, grad: 'BS/MS quantitative',
    exp: 'Strong stats + coding; low-key ML', tags: ['Chicago', 'NYC', 'SG'],
    special: 'Chicago HFT house; low-profile but strong comp.',
    bullets: ['Application often via campus recruiting', 'Crypto arm (Jump Crypto) sometimes lists separately', 'Interview: 3–4 technical rounds'] },
  { id: 'radix-qr', company: 'Radix Trading', role: 'Quantitative Researcher (New Grad)', tier: 'Quant',
    link: 'https://radix.trading/careers/',
    fit: 78, grad: 'MS quantitative or strong BS',
    exp: 'Python/C++, probability, ML', tags: ['Chicago', 'Amsterdam'],
    special: 'Small firm (~150). Fast interview loop.',
    bullets: ['Lower name recognition, comp comparable to bigs', 'Chicago or Amsterdam location', 'Culture: research-heavy, less trader-y'] },
  { id: 'sig-qr', company: 'Susquehanna (SIG)', role: 'Quantitative Researcher / Trader (New Grad)', tier: 'Quant',
    link: 'https://careers.sig.com/',
    fit: 76, grad: 'BS/MS quantitative — 2027 fits',
    exp: 'Game theory / poker mindset; probability', tags: ['Philly', 'Bala Cynwyd'],
    special: 'Poker training on the job. Interview uses game questions.',
    bullets: ['QR and Trader tracks are separate — pick', 'Home-base Bala Cynwyd (near Philly), some NYC', 'New-grad class sizes ~50'] },
  { id: 'imc-tr', company: 'IMC Trading', role: 'Trading / Quant Research (New Grad)', tier: 'Quant',
    link: 'https://careers.imc.com/us/en',
    fit: 70, grad: 'BS/MS quantitative',
    exp: 'Probability + speed; less pure research', tags: ['Chicago', 'Amsterdam'],
    special: 'European origin; strong Chicago office. Faster culture than hedge funds.',
    bullets: ['Trader track leans mental math', 'Research track for physics/ML backgrounds', 'OA is timed and pretty brutal'] },

  { id: 'lbnl-pbf', company: 'LBNL — Berkeley Lab', role: 'Physics Post-Baccalaureate Fellow', tier: 'National Lab',
    link: 'https://jobs.lbl.gov/',
    fit: 82, grad: 'BS holders / MS-in-progress considered for related programs',
    exp: 'Physics research, Python analysis', tags: ['Berkeley CA', 'onsite'],
    special: 'Post-Bac fellowships have short (3–5 day) windows — set alerts on jobs.lbl.gov.',
    bullets: ['Physics Division has recurring post-bac reqs', 'Also look at ATAP, EESA divisions', 'Stepping stone to top PhD programs'] },
  { id: 'lanl-postbac', company: 'LANL — Los Alamos', role: 'Graduate Research Assistant / Post-Bac', tier: 'National Lab',
    link: 'https://lanl.jobs/creative/students',
    fit: 80, grad: 'MS students eligible for Grad Research Assistant appointment during MS',
    exp: 'Programming + physics/math', tags: ['Los Alamos NM', 'onsite'],
    special: 'Q-clearance may apply; US citizen required for most roles.',
    bullets: ['Grad Research Assistant runs during MS program', 'Strong plasma / nuclear / ML groups', 'Housing shortage in Los Alamos — check first'] },
  { id: 'llnl-dssi', company: 'LLNL — Livermore', role: 'Data Science Summer Institute / Postbac', tier: 'National Lab',
    link: 'https://pls.llnl.gov/careers',
    fit: 79, grad: 'MS students eligible; postbac after graduation',
    exp: 'Python, ML, HPC exposure', tags: ['Livermore CA', 'onsite'],
    special: 'US citizen required for most PLS positions; DSSI needs security clearance eligibility.',
    bullets: ['Data Science Summer Institute is 10-week onsite', 'Physics + ML crossover teams active', 'Career-track hires often start via postbac'] },
  { id: 'fermilab-fcsi', company: 'Fermilab', role: 'Computational Science / Research Associate', tier: 'National Lab',
    link: 'https://fermilab.jobs/',
    fit: 78, grad: 'Grad students + new MS grads',
    exp: 'Python, C++, particle physics domain a plus', tags: ['Batavia IL'],
    special: 'FCSI program is 10-week grad internship; RA roles are full-time postgrad.',
    bullets: ['Accelerator + neutrino + CMB-S4 crossovers', 'Chicago-area cost of living', 'Application windows Oct–Jan for summer'] },
  { id: 'nist-nrc', company: 'NIST', role: 'PREP / Guest Researcher tracks', tier: 'National Lab',
    link: 'https://www.nist.gov/pao/nrc-postdoctoral-research-associateships',
    fit: 64, grad: 'NRC requires PhD — but PREP / Guest Researcher may fit MS',
    exp: 'Measurement science, metrology', tags: ['Gaithersburg MD', 'Boulder CO'],
    special: 'NRC is PhD-only; PREP program via CU Boulder is MS-friendly.',
    bullets: ['PREP program via CU Boulder is MS-friendly', 'Metrology + AI/ML measurement teams', 'Federal hiring may be slow — apply early'] },
  { id: 'bnl-ra', company: 'Brookhaven (BNL)', role: 'Research Associate / Assistant', tier: 'National Lab',
    link: 'https://jobs.bnl.gov/',
    fit: 77, grad: 'MS-level Research Assistant + postbac tracks',
    exp: 'Data analysis, Python, physics domain', tags: ['Upton NY', 'onsite'],
    special: 'NSLS-II, RHIC, and CFN attract physics MS grads.',
    bullets: ['Long Island onsite', 'Growing AI-for-science group', 'US person requirement for some roles'] },
  { id: 'ornl-ds', company: 'Oak Ridge (ORNL)', role: 'Research Associate / Data Scientist', tier: 'National Lab',
    link: 'https://jobs.ornl.gov/',
    fit: 74, grad: 'BS/MS with research background',
    exp: 'HPC, ML, physics/materials', tags: ['Oak Ridge TN'],
    special: 'Very strong for AI-for-science, materials, quantum.',
    bullets: ['Frontier exascale system — HPC exposure', 'Quantum computing user program', 'Small city, low cost of living'] },
  { id: 'anl-ra', company: 'Argonne (ANL)', role: 'Research Associate / Applied ML', tier: 'National Lab',
    link: 'https://www.anl.gov/careers',
    fit: 73, grad: 'Postbac + MS-level RA positions posted regularly',
    exp: 'Scientific Python, HPC, ML', tags: ['Lemont IL'],
    special: 'Aurora exascale system; APS light source; strong physics division.',
    bullets: ['Chicago suburbs — commutable', 'Data Science and Learning Division actively hiring', 'Also has Givens Associate summer program'] },

  { id: 'spacex-gnc', company: 'SpaceX', role: 'Software Engineer, GNC / Simulation (New Grad)', tier: 'Aerospace',
    link: 'https://www.spacex.com/careers',
    fit: 81, grad: 'BS/MS in physics/aero/ME/CS',
    exp: 'C++/Python, numerical methods, control theory', tags: ['Hawthorne CA', 'Starbase TX', 'onsite'],
    special: 'US citizen or Green Card required (ITAR). Long hours culture.',
    bullets: ['GNC / dynamics / propulsion sim all take physics grads', 'Interview: coding + numerical + physics fundamentals', 'Pay competitive, equity strong'] },
  { id: 'anduril-swe', company: 'Anduril', role: 'Software Engineer, Autonomy / Perception', tier: 'Aerospace',
    link: 'https://www.anduril.com/careers/',
    fit: 74, grad: 'BS/MS CS + physics dual is welcome',
    exp: 'C++/Rust, computer vision, robotics', tags: ['Costa Mesa CA', 'Boston', 'remote-hybrid'],
    special: 'US citizen typically required. Defense contractor.',
    bullets: ['Fast-growing, well-funded', 'Autonomy / Lattice software stack', 'Some ethical friction on defense — think it through'] },
  { id: 'blueorigin-prop', company: 'Blue Origin', role: 'Propulsion Analysis / Fluid Dynamics Eng', tier: 'Aerospace',
    link: 'https://www.blueorigin.com/careers',
    fit: 70, grad: 'MS in physics/aero preferred',
    exp: 'Fluids, CFD (STAR-CCM+/Fluent), Python', tags: ['Kent WA', 'onsite'],
    special: 'US citizen / Green Card required.',
    bullets: ['Slower cadence than SpaceX, better hours', 'Rocket engine + New Glenn programs', 'Seattle area — high COL but temperate'] },
  { id: 'appmat-rnd', company: 'Applied Materials', role: 'R&D Process / Physics Engineer', tier: 'Semiconductor',
    link: 'https://careers.appliedmaterials.com/',
    fit: 70, grad: 'MS physics/materials/EE',
    exp: 'Semiconductor physics, Python data', tags: ['Santa Clara', 'Austin', 'AZ'],
    special: 'Sponsors visas; H-1B friendly.',
    bullets: ['Process engineer role uses physics background directly', 'Comp modest but stable + full benefits', 'Some fabs on shift schedule'] },
  { id: 'asml-swe', company: 'ASML', role: 'Software / Systems Engineer', tier: 'Semiconductor',
    link: 'https://www.asml.com/en/careers',
    fit: 68, grad: 'MS in physics/EE/CS',
    exp: 'Systems Python/C++; lithography domain a plus', tags: ['San Diego', 'Wilton CT', 'Veldhoven NL'],
    special: 'EUV lithography — physics is the whole product.',
    bullets: ['Multiple US sites', 'Systems SWE role bridges physics and code', "Slower interview loop than tech co's"] },
  { id: 'psiquantum-swe', company: 'PsiQuantum', role: 'Quantum Software / Compiler Engineer', tier: 'Deep Tech',
    link: 'https://www.psiquantum.com/careers',
    fit: 78, grad: 'MS physics/CS with quantum coursework',
    exp: 'Python, compilers, quantum information', tags: ['Palo Alto', 'Chicago', 'hybrid'],
    special: 'Well-funded photonic quantum computing.',
    bullets: ['Applied roles exist alongside pure research', 'Chicago site expanding (near IL Quantum Campus)', 'Physics grads especially welcome'] },
  { id: 'mathworks-edg', company: 'MathWorks', role: 'Engineer Development Group (EDG)', tier: 'Sci Software',
    link: 'https://www.mathworks.com/company/jobs.html',
    fit: 64, grad: 'BS/MS engineering, physics, CS',
    exp: 'MATLAB, Python, one hardware/scientific domain', tags: ['Natick MA', 'hybrid'],
    special: '2-year rotational program → placement in product team.',
    bullets: ['Excellent for MS grads unsure of specialization', 'Boston-area onsite', 'Slower culture, strong work-life'] }
];
